title: Кофейня Nordiclub

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram: nordiclub
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-ki
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
